### ISSUE TITLE
String format issue with python3.4

### ISSUE THREAD

**Issue by adymaharana** [AnthonyMRios/pymetamap#11]
I ran into the following error with PyMetaMap on python 3.4:

> /SubprocessBackend.py", line 80, in extract_concepts
 input_file.write(b'%r|%r\n' % (identifier, sentence))
TypeError:

 unsupported operand type(s) for %: 'bytes' and 'tuple'

And solved it by replacing the input string format with this:
`input_file.write(bytes(str(identifier) + '|' + sentence + '\n', encoding='UTF-8'))`

Bit of a hack, but works!

**Comment by AnthonyMRios** [comment]
Awesome, thanks for letting me know!
