### ISSUE TITLE
extract_concepts not running

### ISSUE THREAD

**Issue by div-94** [AnthonyMRios/pymetamap#12]
from pymetamap import MetaMap
>>> mm = MetaMap.get_instance('/Documents/public_mm/bin/metamap13')
>>> sents = ['Heart Attack', 'John had a huge heart attack']
>>> **concepts,error = mm.extract_concepts(sents,[1,2])**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymetamap/SubprocessBackend.py", line 117, in extract_concepts
    metamap_process = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Getting this error for some time...Please help

**Comment by AnthonyMRios** [comment]
What is your OS?  Are you sure your path is correct to where the metamap binary is located (/Documents/public_mm/bin/metamap13)?

**Comment by div-94** [comment]
i have Ubuntu 16.04... I didn't write the whole path
I'm now getting this error:
/home/student/Documents/public_mm/bin/metamap13.BINARY.Linux: No such file or directory
But when I go to this location...the file is present
I can't what the problem is...I have tried changing SKRun.13  version from 2012 to 2013

**Comment by AnthonyMRios** [comment]
You should point to "/home/student/Documents/public_mm/bin/metamap13"

Can you run this and show me the output?

`ls /home/student/Documents/public_mm/bin/`

**Comment by AnthonyMRios** [comment]
Did you resolve this issue?

**Comment by div-94** [comment]
The problem is in this /home/student/Documents/public_mm/bin/metamap13.BINARY.Linux.

**Comment by AnthonyMRios** [comment]
Can you run metamap from the command line?

If this works, then the wrapper should also run:
https://metamap.nlm.nih.gov/Docs/Metamap13_Usage.shtml

**Comment by RudrakshTuwani** [comment]
For anyone else getting this error too, don't forget to first start the SKR Medpost tagger server!

**Comment by AnthonyMRios** [comment]
Yeah, that is important!
