### ISSUE TITLE
how to set options

### ISSUE THREAD

**Issue by TonicZhang** [AnthonyMRios/pymetamap#13]
Dear Rios,

thanks for your great work, I can run it in my Mac computer now. 
Here I have one more questions:
 where can we set the output options like the metamap originally have, eg: set semtype to dysn only...

**Comment by AnthonyMRios** [comment]
Im out of town right now but you can see supported types in the commens in this file: pymetamap/SubprocessBackend.py

It should be simple to add extra features. If you have any issues, then when i get back i can implement whatever you need

**Comment by TonicZhang** [comment]
I have added one command in SubprocessBckend.py, but ended up with no results output. could you please take a look at my code in the third line which I added?

            command = [self.metamap_filename, '-N']
            command.append('-Q')
            command.append('-J dsyn,neop') # added option for select specific semtype
            command.append(str(composite_phrase))

**Comment by TonicZhang** [comment]
I resolved the problem
that is because I accidentally inserted the new line between "-Q" and the "composite_phrase".
thanks all the same :)

**Comment by AnthonyMRios** [comment]
Awesome! Glad you got it working!
