### ISSUE TITLE
Any support for MetaMapLite version?

### ISSUE THREAD

**Issue by romanegloo** [AnthonyMRios/pymetamap#14]
Hi, Thanks for your great program.

I wonder if you can make your program work with MetaMapLite version. MetaMap tends to be rigorous but slower than the lite version, and it would be nicer if you can support both versions.

**Comment by kaushikacharya** [comment]
@AnthonyMRios 
I have created changes for running MetaMapLite:
https://github.com/kaushikacharya/pymetamap/commit/fff94bb393523da9a9904dbfea7aa87d30aa34e7

Can you please have a look whether this is ok?


As mentioned in [this thread](https://github.com/lhncbc/metamaplite/issues/4), mmi output of Lite doesn't contains a separate "**Location**" field as location is part of "**Trigger Information**" field. Hence had to create corresponding files for MetaMapLite.

Have tested on **MetaMapLite 3.6.1p1**

**Comment by AnthonyMRios** [comment]
Awesome! If you create a pull request, then I can take a look and test the additions before merging.

**Comment by kaushikacharya** [comment]
From the documentation it seemed that option **chemdnersldi** in MetaMapLite corresponds to **sldiID** in MetaMap, but that [doesn't seems to work](https://github.com/lhncbc/metamaplite/issues/7).
Hence index field of concept isn't getting populated with the ids passed in extract_concepts()

**Comment by kaushikacharya** [comment]
@AnthonyMRios 
Update: Issue which I had mentioned in previous post has been corrected.
I was using the wrong input parameter for the input document format.

Have tested on **MetaMapLite 3.6.2rc3**

**Comment by kaushikacharya** [comment]
@AnthonyMRios
Did you got a chance to review my changes?

**Comment by AnthonyMRios** [comment]
Not in detail. I have a paper deadline coming up. I should have some time to review/commit the changes this weekend.
