### ISSUE TITLE
metamap

### ISSUE THREAD

**Issue by chandana1996** [AnthonyMRios/pymetamap#19]
<img width="1280" alt="screen shot 2017-07-28 at 5 12 40 pm" src="https://user-images.githubusercontent.com/30526383/28715966-4e05c090-73b8-11e7-9ec6-59231773d624.png">
I am getting output as empty list instead i should get list containing concepts could you please help me out with this . I want the similar output as yours.Does this code need any servers in metamap to run in the background?

**Comment by AnthonyMRios** [comment]
You should start the SKR/Medpost Part-of-Speech Tagger Server and the Word Sense Disambiguation (WSD) Server.

Also, you must point to "/Users/chandana/Desktop/public_mm/bin/metamap16" instead of "/Users/chandana/Desktop/public_mm/bin/metamap16.BINARY.Darwin".

Let me know if this solves your issues. If not, we can try to figure out the issue.

**Comment by chandana1996** [comment]
can u tell me how to start the servers on mac i used the command "skrmedpostctl start" after pointing to the bin directory?
but it is giving me unknown command

**Comment by chandana1996** [comment]
thanks i got it now i will approach u when ever needed.

**Comment by AnthonyMRios** [comment]
I believe that should work. I will test on my mac in a few hours and let you know for sure.

In the meantime, did you change the file you are pointing to in the get_instance method? "metamap16.BINARY.Darwin" to "metamap16".

**Comment by AnthonyMRios** [comment]
I'm glad you got it working! Can you post what the issue was in case others encounter the same problem?

**Comment by chandana1996** [comment]
My issue was i got empty string as output but i figured that i should start medpost and wsd server and my issue got resolved.
