### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Gracelek** [AnthonyMRios/pymetamap#21]
When I run the example code, I got this error below. 
Any idea?

> dyld: Library not loaded: /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.dylib
  Referenced from: /users/gracelee/documents/metamap/public_mm/bin/metamap14.BINARY.Darwin
  Reason: image not found
/users/gracelee/documents/metamap/public_mm/bin/metamap2014.TEMPLATE: line 146: 95257 Abort trap: 6           $COMMAND

**Comment by AnthonyMRios** [comment]
I have not seen that error before. It looks like it may be a problem with your metamap installation. Can you run metamap via command line? Also, make sure you have started the SKR/Medpost Part-of-Speech Tagger Server and the Word Sense Disambiguation (WSD) Server.

**Comment by Gracelek** [comment]
When I try an example of MetaMap, it gives the same error.
For the last few hours I googled for the solution but still I haven't solved it.
Btw thank you for the prompt response.

**Comment by AnthonyMRios** [comment]
If there is an issue with your metamap installation, then I probably won't
be much help. Are you using a mac or linux machine?

Anthony

**Comment by Gracelek** [comment]
Hi Anthony
I am using Mac Sierra. I will fix MetaMap problem first and then come back to use the pymetamap!
I am closing the issue.
-G
