### ISSUE TITLE
Need help in running python wrapper for metamap

### ISSUE THREAD

**Issue by patniharshit** [AnthonyMRios/pymetamap#22]
> mm = MetaMap.get_instance('/opt/public_mm/bin/metamap12')

I cannot understand what do you mean by metamap binary? Can you share the link for downloading metamap binary?

I have following files in /public_mm/bin/ directory but couldn't figure out which one is binary:

>db_access.so metamap16.BINARY.Linux   nls_signal.so	 SKRrun.16.in
ginstall.tcl  metamap16.in	       qp_lexicon.so	 uninstall.sh.in
install.log   metamap16.sav	       qp_morph.so	 wsdserverctl.in
install.sh    metamap2016.TEMPLATE.in  SKRenv.16.in
install.tcl   metamap.in	       skrmedpostctl.in

**Comment by AnthonyMRios** [comment]
You must download and install metamap from here: https://metamap.nlm.nih.gov/MainDownload.shtml

After you have successfully installed metamap, then I can help you use my wrapper.

**Comment by AnthonyMRios** [comment]
Actually, the file for you will be called metamap16.

**Comment by patniharshit** [comment]
Ok, I have installed it and as you pointed out binary for me is metamap16.
Now when I try to run it, I get following error:

> Berkeley DB databases (USAbase 2016AA strict model) are open.
Static variants will come from table varsan in /home/harshit/Desktop/Monsoon17/IRE/MajorProject/public_mm/DB/DB.USAbase.2016AA.strict.
Derivational Variants: Adj/noun ONLY.
Variant generation mode: static.
>
>### MetaMap ERROR: Calling socket_client_open for TAGGER Server on host localhost and port 1795:
>error(system_error,system_error(SPIO_E_NET_CONNREFUSED))
>None

**Comment by AnthonyMRios** [comment]
You should start the SKR/Medpost Part-of-Speech Tagger Server and the Word Sense Disambiguation (WSD) Server.

```
$ ./bin/skrmedpostctl start
$ ./bin/wsdserverctl start
```

**Comment by patniharshit** [comment]
Thanks for the help.
Maybe writing that in ReadMe would help.

**Comment by AnthonyMRios** [comment]
No problem. I'm glad you got everything installed. I will add a link to the MetaMap installation instructions.

**Comment by LeiGong0125Carrot** [comment]
> No problem. I'm glad you got everything installed. I will add a link to the MetaMap installation instructions.

Hello, I got metamap installed and start the two server, when I tried to run the semrep, the same error occured
