### ISSUE TITLE
Metamap Installation Issue

### ISSUE THREAD

**Issue by ghost** [AnthonyMRios/pymetamap#23]
Metamap version: 2014 for linux
System: Ubuntu 16.04 LTS
JAVA:1.8 jre
I was following the metamap installation instruction from  **https://metamap.nlm.nih.gov/Installation.shtml**. 
But when I test **echo "lung cancer" | ./bin/metamap -I** ,  I got 
Control options:
  composite_phrases=4
  lexicon=db
  mm_data_year=2014AA
  show_cuis
Processing 00000000.tx.1: lung cancer

Phrase: lung cancer
Meta Mapping (1000):
  1000   C0684249:LUNG CANCER (Carcinoma of lung) [Neoplastic Process]
Meta Mapping (1000):
  1000   C0242379:Lung Cancer (Malignant neoplasm of lung) [Neoplastic Process]
Unlike what I looks like in the instruction:
Phrase: "lung cancer"
Meta Candidates (8):
  1000 C0242379:Lung Cancer (Malignant neoplasm of lung) [Neoplastic Process]
  1000 C0684249:Lung Cancer (Carcinoma of lung) [Neoplastic Process]
   861 C0006826:Cancer (Malignant Neoplasms) [Neoplastic Process]
   861 C0024109:Lung [Body Part, Organ, or Organ Component]
   861 C0998265:Cancer (Cancer Genus) [Invertebrate]
   861 C1278908:Lung (Entire lung) [Body Part, Organ, or Organ Component]
   861 C1306459:Cancer (Primary malignant neoplasm) [Neoplastic Process]
   768 C0032285:Pneumonia [Disease or Syndrome]
Meta Mapping (1000):
  1000 C0684249:Lung Cancer (Carcinoma of lung) [Neoplastic Process]
Meta Mapping (1000):
  1000 C0242379:Lung Cancer (Malignant neoplasm of lung) [Neoplastic Process]

And my servers works fine:
wei@wei-OptiPlex-790:/opt/public_mm$ sudo ./bin/skrmedpostctl start
$Starting skrmedpostctl: 
started.
wei@wei-OptiPlex-790:/opt/public_mm$ sudo ./bin/wsdserverctl start
$Starting wsdserverctl: 
started.
wei@wei-OptiPlex-790:/opt/public_mm$ loading properties file /opt/public_mm/WSD_Server/config/disambServer.cfg
WSD Server initializing disambiguation methods.
WSD Server databases and disambiguation methods have been initialized.

I totally dont understand.
Please Help!

**Comment by ghost** [comment]
@AnthonyMRios  Hi Anthony I hope you can help me because I am trying to use your pymetamap

**Comment by AnthonyMRios** [comment]
What are you trying to do? It looks like you have correctly installed MetaMap. If you are worried about having multiple entities for "lung cancer", then you can use word sense disambiguation (the -y option).

If you want to  use pymetamap, then you just need to point to the binary where you installed metamap. From your examples above, it should be something like
```
mm = MetaMap.get_instance('/opt/public_mm/bin/metamap16')
```
depending on what version you have installed.

**Comment by ghost** [comment]
The problem is that the WSD server started:

_wei@wei-OptiPlex-790:/opt/public_mm$ sudo ./bin/wsdserverctl start
$Starting wsdserverctl:
started.
wei@wei-OptiPlex-790:/opt/public_mm$ loading properties file /opt/public_mm/WSD_Server/config/disambServer.cfg
WSD Server initializing disambiguation methods.
WSD Server databases and disambiguation methods have been initialized_

However, seems like the WSD server does not work.

**Comment by AnthonyMRios** [comment]
Sorry, maybe I'm not seeing the error. It looks like it is saying the WSD Server has been initialized. Do you get an error when you try to use word sense disambiguation (WSD)?

**Comment by ghost** [comment]
I just followed the installation instruction.  When installing, no errors for WSD.
How can I test WSD?

**Comment by AnthonyMRios** [comment]
If you want to use WSD with my python wrapper, then you can use this:
```
mm = MetaMap.get_instance('/opt/public_mm/bin/metamap16', word_sense_disambiguation=True)
```
If you want to test it from command line, then you need to set the -y command line option. You can see more about that here: https://metamap.nlm.nih.gov/Docs/MM_2016_Usage.pdf

**Comment by ghost** [comment]
Thank you so much I will check

**Comment by AnthonyMRios** [comment]
Did you fix any issues you were having? If so, I will go ahead and close this issue.

**Comment by ghost** [comment]
Sorry. Can you give me one more day? Because I am working on another
project recently

**Comment by AnthonyMRios** [comment]
Sure. No problem.

**Comment by ghost** [comment]
Sorry I got this:
>>> from pymetamap import MetaMap
>>> mm = MetaMap.get_instance('/opt/public_mm/bin/metamap14', word_sense_disambiguation=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pymetamap-0.1-py3.5.egg/pymetamap/MetaMap.py", line 44, in get_instance
    return SubprocessBackend(**extra_args)
TypeError: __init__() got an unexpected keyword argument 'word_sense_disambiguation'

**Comment by AnthonyMRios** [comment]
Sorry, I misinformed you. The argument "word_sense_disambiguation", should be passed to extract_concepts, not get_instance.

**Comment by ghost** [comment]
I changed to use Java API. Thank you for helping me.
