### ISSUE TITLE
change source

### ISSUE THREAD

**Issue by deepak-k-zefr** [AnthonyMRios/pymetamap#25]
Hi Anthony,

Firstly thank you for making this API. I wanted to know if there is a way to restrict matches to a certain vocabulary. This is the set of vocabularies  options I can select in Batch Metamap (https://ii.nlm.nih.gov/vocabs/1718/RsourceFrame_USAbase.html).

Thanks,
Deepak

**Comment by AnthonyMRios** [comment]
Hi Deepak,

Do you mean the data version? To set the data version, you can do the following:

`mm.extract_concepts(sents,[1,2],mm_data_version="NLM")`

If you want to restrict to specific sources, I have created a new branch (filterSources) that you can use. To restrict to specific sources with the new branch, you can do the following:

`mm.extract_concepts(sents,[1,2],restrict_to_sources=["MSH","SNOMED_CT"])`

I have not tested the last option, so let me know if you have any issues.

**Comment by deepak-k-zefr** [comment]
Thanks, Anthony! I am not sure what you mean by if I meet the data version.
I tried the following: 
`mm.extract_concepts(sents,[1,2],mm_data_version="NLM")`

and got the output:

`([], None)`

which probably means I don't meet the data version.

**Comment by AnthonyMRios** [comment]
meet -> mean

I will need to test it later to see if there is an issue. Does it return anything when you use the metamap command line interface with the -V option?

https://metamap.nlm.nih.gov/Docs/MM_2016_Usage.pdf

**Comment by deepak-k-zefr** [comment]
Good catch, Anthony!  I tried to tun the following:
` ./metamap16 NLM -V test.txt `

I got the error: 
`### MetaMap ERROR: For the 2016AA release, the valid models are: [USAbase]`

I am downloading the `2017AB UMLS NLM Datasets`. I will let you know how it goes after that.

I will make a pull request to the new branch if I can make it work.

Thanks,
Deepak

**Comment by deepak-k-zefr** [comment]
I wanted to check if you were using the 2016 version of metamap when you set the `mm_data_version="NLM"`

Thanks,
Deepak

**Comment by AnthonyMRios** [comment]
I did not set it to NLM recently. I was just showing an example of changing the data version. By the way, to change the data year version, you will need to add the -Z option to the SubprocessBackend.py file.

**Comment by deepak-k-zefr** [comment]
Thanks @AnthonyMRios. I wrongly misunderstood that I need to set the data version to "NLM" to access other vocabularies.

I have tested the `restrict_to_sources` functionality. I can attest that it works.

To anybody visiting this page later:
Here are some results:
```
sents = ['Heart Attack', 'John had a huge heart attack']
concepts,error = mm.extract_concepts(sents,[1,2],restrict_to_sources=["SNOMEDCT_US"])
for concept in concepts:
     print (concept)
```
```
ConceptMMI(index='1', mm='MMI', score='14.64', preferred_name='Myocardial Infarction', cui='C0027051', semtypes='[dsyn]', trigger='["Myocardial infarction, NOS"-tx-1-"Heart Attack"-noun-0]', location='TX', pos_info='1/12', tree_codes='C14.280.647.500;C14.907.585.500')
ConceptMMI(index='1', mm='MMI', score='6.83', preferred_name='Heart', cui='C0018787', semtypes='[bpoc]', trigger='["Heart"-tx-1-"Heart"-noun-0]', location='TX', pos_info='1/5', tree_codes='A07.541')
ConceptMMI(index='1', mm='MMI', score='3.68', preferred_name='Entire heart', cui='C1281570', semtypes='[bpoc]', trigger='["Entire heart"-tx-1-"Heart"-noun-0]', location='TX', pos_info='1/5', tree_codes='')
ConceptMMI(index='1', mm='MMI', score='3.68', preferred_name='Observation of attack', cui='C1304680', semtypes='[fndg]', trigger='["Attack"-tx-1-"Attack"-noun-0]', location='TX', pos_info='7/6', tree_codes='')
ConceptMMI(index='1', mm='MMI', score='3.68', preferred_name='Onset of illness', cui='C0277793', semtypes='[tmco]', trigger='["Onset of illness"-tx-1-"Attack"-noun-0]', location='TX', pos_info='7/6', tree_codes='')
ConceptMMI(index='2', mm='MMI', score='13.22', preferred_name='Myocardial Infarction', cui='C0027051', semtypes='[dsyn]', trigger='["Myocardial infarction, NOS"-tx-1-"heart attack"-noun-0]', location='TX', pos_info='17/12', tree_codes='C14.280.647.500;C14.907.585.500')
ConceptMMI(index='2', mm='MMI', score='6.79', preferred_name='Heart', cui='C0018787', semtypes='[bpoc]', trigger='["Heart"-tx-1-"heart"-noun-0]', location='TX', pos_info='17/5', tree_codes='A07.541')
ConceptMMI(index='2', mm='MMI', score='3.63', preferred_name='Entire heart', cui='C1281570', semtypes='[bpoc]', trigger='["Entire heart"-tx-1-"heart"-noun-0]', location='TX', pos_info='17/5', tree_codes='')
ConceptMMI(index='2', mm='MMI', score='3.63', preferred_name='Observation of attack', cui='C1304680', semtypes='[fndg]', trigger='["Attack"-tx-1-"attack"-noun-0]', location='TX', pos_info='23/6', tree_codes='')
ConceptMMI(index='2', mm='MMI', score='3.63', preferred_name='Onset of illness', cui='C0277793', semtypes='[tmco]', trigger='["Onset of illness"-tx-1-"attack"-noun-0]', location='TX', pos_info='23/6', tree_codes='')
```

and for MESH vocabulary:

```
sents = ['Heart Attack', 'John had a huge heart attack']
concepts,error = mm.extract_concepts(sents,[1,2],restrict_to_sources=["SNOMEDCT_US"])
for concept in concepts:
     print (concept)
```


```
ConceptMMI(index='1', mm='MMI', score='14.64', preferred_name='Myocardial Infarction', cui='C0027051', semtypes='[dsyn]', trigger='["Myocardial Infarction"-tx-1-"Heart Attack"-noun-0]', location='TX', pos_info='1/12', tree_codes='C14.280.647.500;C14.907.585.500')
ConceptMMI(index='1', mm='MMI', score='6.83', preferred_name='Heart', cui='C0018787', semtypes='[bpoc]', trigger='["Heart"-tx-1-"Heart"-noun-0]', location='TX', pos_info='1/5', tree_codes='A07.541')
ConceptMMI(index='2', mm='MMI', score='13.22', preferred_name='Myocardial Infarction', cui='C0027051', semtypes='[dsyn]', trigger='["Myocardial Infarction"-tx-1-"heart attack"-noun-0]', location='TX', pos_info='17/12', tree_codes='C14.280.647.500;C14.907.585.500')
ConceptMMI(index='2', mm='MMI', score='6.79', preferred_name='Heart', cui='C0018787', semtypes='[bpoc]', trigger='["Heart"-tx-1-"heart"-noun-0]', location='TX', pos_info='17/5', tree_codes='A07.541')```


You can get the list of vocabularies here: https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html

**Comment by AnthonyMRios** [comment]
Great! I'm glad you got what you needed. Thanks for posting the code snippets. I will merge the new branch.
