### ISSUE TITLE
Interpreting SCORE

### ISSUE THREAD

**Issue by deepak-k-zefr** [AnthonyMRios/pymetamap#26]
Is there a way to interpret the scores that I get from `pymetamap`. I see that I get different scores for matches from metamap run on the command line and from the pymetamap. I assume this is because of different default settings in each case.
I am trying to see if I can set a certain threshold and filter bad matches. I dont know if this approach is correct.

Example:

`text: John had a huge heart attack`

metamap command line:
`score=901`
output:
   `901   -- Heart Attack (Myocardial Infarction) [Disease or Syndrome]`

pymetamap:
`Score=13.22`
output:
`ConceptMMI(index='2', mm='MMI', score='13.22', preferred_name='Myocardial Infarction', cui='C0027051', semtypes='[dsyn]', trigger='["-- Heart Attack"-tx-1-"heart attack"-noun-0]', location='TX', pos_info='17/12', tree_codes='C14.280.647.500;C14.907.585.500')`

Thanks,
Deepak

**Comment by AnthonyMRios** [comment]
The score is from metamaps MMI format. For more information about that please see the following document: https://metamap.nlm.nih.gov/Docs/MMI_Output_2016.pdf

**Comment by deepak-k-zefr** [comment]
Thanks, Anthony.  The scoring process looks like pretty complicated, I have to manually look at the matches to make sure the matches are correct.

To people who visit this page later, here is the link to the algorithm: https://ii.nlm.nih.gov/MTI/Details/mmi.shtml
