### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by chaojiang06** [AnthonyMRios/pymetamap#28]
Hi Anthony,

Thanks for your great program! It is super convenient and easy to use!

I have successfully installed everything and was trying to run that Example Usage. However, I got a TypeError like this:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pymetamap/SubprocessBackend.py", line 123, in extract_concepts
>     command.append(str(','.join(exclude_sources)))

I try to print the exclude_resources and command, it looks like:
> (False, ['/project/public_mm/bin/metamap16', '-N', '-Q', '4', '-e'])

So basically the exclude_resources is False, it can't be joined by the string method.

Would you please take a look at this error, was I making any mistake?

Thanks a million!

**Comment by AnthonyMRios** [comment]
I apologize for a bug in a recent update I pushed. Please try now. Let me know if you have any more issues.

**Comment by chaojiang06** [comment]
Thanks so much for updating so fast, let me try!

Thanks again for your response and help!

**Comment by chaojiang06** [comment]
It works perfectly!

Thanks Anthony!
