### ISSUE TITLE
what is the utility of backend='subprocess'

### ISSUE THREAD

**Issue by chaojiang06** [AnthonyMRios/pymetamap#29]
Hi Dear Anthony,

Thanks for your great software, I have another two quick questions that, 

1. what is the utility of 

> backend='subprocess'?

Because when I using pymetamap to extract concepts, the screen will show a lot of intermediate processes, is this 'backend='subprocess'' used to make the process silent?

2. Is it possible to get concepts by multi-threading?

Because I am working on a pretty large dataset, thus if I extract their concepts one by one, it will take pretty long time, thus I am thinking is there any chance to use the python multi-threading feature, like this:

> from multiprocessing import Pool
> p = Pool(5)
> def f(x):       <--------------in the function I will extract concepts
...     return x*x 
...
> p.map(f, [1,2,3])

Thanks a million in advance!

**Comment by AnthonyMRios** [comment]
Hi Chao6,

The backend parameter only works with the subprocess command right now. The reason for the backend parameter is that I have future plans to wrap the complete Metamap java interface and I was trying to make sure I do not have to rewrite the basic structure of my code. I don't have a method to make everything silent.

You should be able to use the multiprocessing concepts in python. I don't have code to do this, so you would need to write it yourself. You will probably need to close processes that take too long to run and handle ghost processes. When I was playing with this in the past, I had issues with cleanup, but that should not be too much of a problem.

**Comment by chaojiang06** [comment]
Hi, I have tried the multi-threads feature and it worked perfectly. 
No goest process!

Thanks for your excellent work!

**Comment by AnthonyMRios** [comment]
I'm glad it all worked out for you! Feel free to make a pull request if you have time ;)
