### ISSUE TITLE
 __new__() takes exactly 11 arguments (9 given)

### ISSUE THREAD

**Issue by vsocrates** [AnthonyMRios/pymetamap#3]
Hi, this is similar to the closed Issue, but I am also having trouble getting a particular list of sentences to return MetaMap concepts. I tried debugging this myself, but couldn't figure it out. I did make a little progress though:

With the following list of sentences: 

`test = ['The patient stated that her general practitioner (GP) and specialist did not think that the problems were the side effects of domperidone.', 'No further information was reported at the time of the report.', 'Other reference number include - MHRA: 01001307081; 01001307081: GB-JNJFOC-20150407438.', 'Duration of suspect drug "Domperidone" was reported as 5 years.', '"No medical assessment".']` :

`concepts, error = mm.extract_concepts(test[0])` 

and 

`concepts, error = mm.extract_concepts(test[1])`

both work, but 

`concepts, error = mm.extract_concepts(test[0:1])` throws the error that I mentioned in the title. Full stack track reproduced below:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/vsocrates/venv/lib/python2.7/site-packages/pymetamap-0.1-py2.7.egg/pymetamap/SubprocessBackend.py", line 132, in extract_concepts
    concepts = Corpus.load(output.splitlines())
  File "/work/vsocrates/venv/lib/python2.7/site-packages/pymetamap-0.1-py2.7.egg/pymetamap/Concept.py", line 39, in load
    corpus.append(Concept.from_mmi(line))
  File "/work/vsocrates/venv/lib/python2.7/site-packages/pymetamap-0.1-py2.7.egg/pymetamap/Concept.py", line 30, in from_mmi
    return this_class(**dict(zip(FIELD_NAMES, fields)))
TypeError: __new__() takes exactly 11 arguments (9 given)
__new__() takes exactly 11 arguments (9 given)
```

Thank you for your help!

**Comment by vsocrates** [comment]
I'm sorry, I have a few more details:

I found that it has to do with a specific output that MetaMap has for acronyms/abbreviations (AA)-type concepts. On the second page of this doc: https://metamap.nlm.nih.gov/Docs/MMI_Output_2016.pdf, you can see that the number of fields is 1 less than the ones used under `Concept.py`. Moreover, the output for (in my case), the text "medical practitioner" was the following: 

`00000000|AA|GP|general practitioner|1|2|3|20`, which as you can see only has 8 fields (missing `pos_info` field). This was the error I was getting. I resolved it by including some dummy values for the other two fields, but I'm not sure how to fix it in the library, otherwise I would have made a pull request and fixed it myself. 

Please let me know if you need more information. Thanks!

**Comment by AnthonyMRios** [comment]
Hi @vsocrates. Thanks for all the information. I just pushed a branch aa_concept. I don't have metamap 2016 installed right now. Do you mind cloning that branch and testing it to see if you still get the error?

I have added 3 types of concepts now: MMI, AA, and UA.

**Comment by AnthonyMRios** [comment]
Just tested with newest MetaMap. The current branch should fix you issues. If it works for you I will merge the pull request.

**Comment by AnthonyMRios** [comment]
#4

**Comment by vsocrates** [comment]
I actually have MetaMap 2014 so I can't test it either, but it appears to work. Thanks!

**Comment by AnthonyMRios** [comment]
np. I went ahead and merged the updates.
