### ISSUE TITLE
Term processing / restrict to semantic types

### ISSUE THREAD

**Issue by eddiepease** [AnthonyMRios/pymetamap#30]
Hi - thank you for such an awesome tool! Comparing the tool with the metamap UI, there seem to be a few parameters missing such as:

Being able to only return certain semantic types
Option to select term processing / overmatches / concept gaps

Would it be possible to add these to 'SubprocessBackend.py'?

**Comment by AnthonyMRios** [comment]
Hi - Sure these can be added. I will add them today or tomorrow. If you have added them already to your local copy, feel free to make a pull request.

**Comment by kaushikacharya** [comment]
@AnthonyMRios 
   Created a [pull request](https://github.com/AnthonyMRios/pymetamap/pull/33) with the option parameters requested by @eddietheeagle1
