### ISSUE TITLE
Accessing elements within extract_concepts

### ISSUE THREAD

**Issue by haleyhowe** [AnthonyMRios/pymetamap#34]
Hello Anthony,

Your python wrapper package is great. Quick question: Is there a way to access specific concept attributes within the list that is outputted by the extract_concepts function?

Thanks for all your help.

Haley Howell

**Comment by AnthonyMRios** [comment]
Hi Haley,

Which attribute are you wanting to access? To get something like the preferred name, you can do something like 

```
>>> sents = ['Heart Attack', 'John had a huge heart attack']
>>> concepts,error = mm.extract_concepts(sents,[1,2])
>>> for concept in concepts:
...     print(concept.preferred_name)
```

If you are talking about the trigger_info, then you would need to parse what you need out. Something like the following should work, I think:

```
trigg = concept.trigger_info.split('-')
print(trigg) # Should be a list of items
```

I hope that answers your question.

Anthony

**Comment by haleyhowe** [comment]
Anthony,

Thanks for getting back to me. This helps a lot! 

Haley Howell

**Comment by AnthonyMRios** [comment]
Glad to help.
