### ISSUE TITLE
MetaMap ERROR

### ISSUE THREAD

**Issue by Annztt** [AnthonyMRios/pymetamap#41]
>>> concepts,error = mm.extract_concepts(sents,[1,2])
Berkeley DB databases (USAbase 2018AB strict model) are open.
Static variants will come from table varsan in /home/ztt/NYTexperiments/pymetamap-master/public_mm/DB/DB.USAbase.2018AB.strict.
Derivational Variants: Adj/noun ONLY.
Variant generation mode: static.

### MetaMap ERROR: Calling socket_client_open for TAGGER Server on host localhost and port 1795:
error(system_error,system_error(SPIO_E_NET_CONNREFUSED))
--------------------------------------------------------------------------------------
Hello，how can I solve the problem above?

**Comment by AnthonyMRios** [comment]
Fix your problem?
