### ISSUE TITLE
MetaMap Error

### ISSUE THREAD

**Issue by fault-lines** [AnthonyMRios/pymetamap#46]
Hey Anthony, thanks a lot for this making this really useful wrapper. I've installed MetaMap and cloned your repository, however when I run
`mm= MetaMap.get_instance('/Users/usr/Downloads/metamapfolder/public_mm/bin/metamap18')`

`mm.extract_concepts('some sentence')`

I get the following error:
`MetaMap ERROR: Calling socket_client_open for TAGGER Server on host localhost and port 1795:
error(system_error,system_error(SPIO_E_NET_CONNREFUSED))`

I know this might not be related to pymetamap but to MetaMap itself, but maybe you know what the issue could be? 

Thanks a lot and all the best.

**Comment by zzachw** [comment]
Hi, I think you should start the SKR/Medpost Part-of-Speech Tagger Server and the Word Sense Disambiguation (WSD) Server.
```
./bin/skrmedpostctl start
./bin/wsdserverctl start
```

[FYI](https://github.com/AnthonyMRios/pymetamap/issues/22#issuecomment-340069661)

**Comment by AnthonyMRios** [comment]
Yep, it looks like you need to start the PoS and WSD servers.

**Comment by fault-lines** [comment]
I had problems running those because of some java issues, but got it solved now - thanks a lot!!

**Comment by vijetadeshpande** [comment]
I am having this issue even after starting both servers (POS and WSD). Is it related to Mac not allowing some java processes to run?
