### ISSUE TITLE
Different order return different number of concept

### ISSUE THREAD

**Issue by yihengpan** [AnthonyMRios/pymetamap#49]
Hi Anthony,

Thanks for your great work! That's really helpful since I can do all the implementation in python without switching.
The issue for me is every time I shuffle the sentence list, the number of concepts is different. And if I run metamap again on  the non-recognizable words, some turn to be recognized, which makes me confused.

So in my implementation, I have to run metamap constantly on the currently non-recognized sentences until there's no concept return. Actually, I'm still not confident about this approach and kind of worried about what's going on.

For example, there are 1000 sentences in my list. I use extract_concept and there are 379 results. And I run extract_concept again on the remaining 621 results, it returns 89 results this time. I keep running on the remaining until it returns no concept.

I am not sure it's problem with metamap or pymetamap. Let me know if you have any thoughts! Thanks in advance!

Best,
Yiheng

**Comment by AnthonyMRios** [comment]
Hi Yiheng,

Can you share some test cases and a short script  so I can try to reproduce your error? I can take a look and see if I can pinpoint the problem.

Anthony

**Comment by yihengpan** [comment]
Yes. I'm trying to recognize the drug names from [FAERS](https://www.fda.gov/drugs/questions-and-answers-fdas-adverse-event-reporting-system-faers/fda-adverse-event-reporting-system-faers-public-dashboard) drug list.

After setting up pymetamap, code starts here:

import random

druglist = ['Epoetin Beta',
 'SEROQUIL',
 'SODIUM CHLORIDE',
 'panitumumab',
 'TESSALON PERLE',
 'SULFAMETHOXAZOLE AND TRIMETHOPRIM',
 'BISACODYL',
 'VIT D',
 'ASTELIN',
 'NEXOIM',
 'CATABON',
 'VFEND',
 'MEVALOTIN',
 'Sunitinib Malate',
 'LISINOPRIL AND HYDROCHLOROTHIAZIDE',
 'NITROGLYCERIN "A.L."',
 'NORVASC                         ',
 'MOBIC',
 "ST. JOHN'S WORT",
 'POLARAMIN',
 'OSCAL',
 'VENTOLIN',
 'ADONA',
 'AGGRENOX',
 'ERBITUX SOLN FOR INF 5MG/ML',
 'HYPEN',
 'VOLTAREN                           /00372303/',
 'ZOLMITRIPTAN',
 '5-ASA',
 'OCTREOTIDE',
 'Botox�',
 'TRANSAMIN',
 'TIZANIDINE',
 'DAPSONE',
 'ANTIBIOTIC, NAME UNKNOWN',
 'Peg-Interferon Alfa 2a',
 'MIRAPEX',
 'XOPENEX',
 'NEUTROGIN',
 'PROGRAF',
 'HYDROCHLOROTH',
 'ATENOLOL TABS',
 'NAIXAN',
 'CLONIDINE PATCH',
 'CETRIZINE',
 'HABEKACIN',
 'RESTASIS',
 'METAMUCIL',
 'Erlotinib',
 'ALDACTONE-A',
 'SOLSUMAX',
 'ARMOUR THYROID',
 'MODACIN',
 'ESTROGEN',
 'VIVELLE-DOT',
 'ESTROGEN NOS',
 'DASATINIB',
 'HUMIRA 40 MG/0.8 ML PEN',
 'Coreg',
 'FENOFIBRATE',
 'METHYCOBAL',
 'KCL',
 'FIRSTCIN',
 'ACTIVASE "GENENTECH"',
 'ANTILYMPHOCYTE GLOBULIN',
 'MYSLEE',
 'NOVAMIN',
 'DEPO-MEDROL',
 'Vfend',
 'GRAN',
 'BLOOD HUMAN',
 'BLOOD TRANSFUSION',
 'SPIRIVA HANDIHALER',
 'PROBIOTICS',
 'DOXYRUBICIN HCL',
 'ADDERALL',
 'AMOXAN',
 'DESYREL',
 'VITAMIN B-12',
 'ATROPINE SULFATE',
 'AMIKACIN SULFATE',
 'G-CSF',
 'PROVIDAL',
 'TRAMACET',
 'SINUTAB "ACHE"',
 'ZOLEDRONIC ACID',
 'TAZORAC',
 'IXABEPILONE',
 'SOLU-MEDROL',
 'CENTRUM                            /00554501/',
 'BLOOD PRESSURE, NAME UNKNOWN',
 'LEVSIN',
 'KLONIPIN',
 'SELENIUM',
 'GLUFAST',
 'TERAZOSIN',
 'Ribavirin',
 'BONALON 5MG',
 'MOEXIPRIL',
 'TAMSULOSIN HCL']
concept_1,error = mm.extract_concepts(druglist,list(range(0,len(druglist))), 
                                        restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
                                                         'chvs','clnd','elii','enzy','hops','horm',
                                                         'imft','irda','inch','nnon','phsu','orch','vita'
                                                        ])
random.shuffle(druglist)
concept_2,error = mm.extract_concepts(druglist,list(range(0,len(druglist))), 
                                        restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
                                                         'chvs','clnd','elii','enzy','hops','horm',
                                                         'imft','irda','inch','nnon','phsu','orch','vita'
                                                        ])
print(len(concept_1), len(concept_2))

**Comment by yihengpan** [comment]
The results for me is 30 and 19. You can see just shuffle the drug list, the number of concepts changes.

**Comment by AnthonyMRios** [comment]
I checked MetaMapLite. It gives consistent answers---104 before and after shuffling. I will check the standard MetaMap version tomorrow. What version of MetaMap are you using?

```
import random
from pymetamap import MetaMapLite

def main():
    druglist = ['Epoetin Beta',
    'SEROQUIL',
    'SODIUM CHLORIDE',
    'panitumumab',
    'TESSALON PERLE',
    'SULFAMETHOXAZOLE AND TRIMETHOPRIM',
    'BISACODYL',
    'VIT D',
    'ASTELIN',
    'NEXOIM',
    'CATABON',
    'VFEND',
    'MEVALOTIN',
    'Sunitinib Malate',
    'LISINOPRIL AND HYDROCHLOROTHIAZIDE',
    'NITROGLYCERIN "A.L."',
    'NORVASC ',
    'MOBIC',
    "ST. JOHN'S WORT",
    'POLARAMIN',
    'OSCAL',
    'VENTOLIN',
    'ADONA',
    'AGGRENOX',
    'ERBITUX SOLN FOR INF 5MG/ML',
    'HYPEN',
    'VOLTAREN /00372303/',
    'ZOLMITRIPTAN',
    '5-ASA',
    'OCTREOTIDE',
    'Botox�',
    'TRANSAMIN',
    'TIZANIDINE',
    'DAPSONE',
    'ANTIBIOTIC, NAME UNKNOWN',
    'Peg-Interferon Alfa 2a',
    'MIRAPEX',
    'XOPENEX',
    'NEUTROGIN',
    'PROGRAF',
    'HYDROCHLOROTH',
    'ATENOLOL TABS',
    'NAIXAN',
    'CLONIDINE PATCH',
    'CETRIZINE',
    'HABEKACIN',
    'RESTASIS',
    'METAMUCIL',
    'Erlotinib',
    'ALDACTONE-A',
    'SOLSUMAX',
    'ARMOUR THYROID',
    'MODACIN',
    'ESTROGEN',
    'VIVELLE-DOT',
    'ESTROGEN NOS',
    'DASATINIB',
    'HUMIRA 40 MG/0.8 ML PEN',
    'Coreg',
    'FENOFIBRATE',
    'METHYCOBAL',
    'KCL',
    'FIRSTCIN',
    'ACTIVASE "GENENTECH"',
    'ANTILYMPHOCYTE GLOBULIN',
    'MYSLEE',
    'NOVAMIN',
    'DEPO-MEDROL',
    'Vfend',
    'GRAN',
    'BLOOD HUMAN',
    'BLOOD TRANSFUSION',
    'SPIRIVA HANDIHALER',
    'PROBIOTICS',
    'DOXYRUBICIN HCL',
    'ADDERALL',
    'AMOXAN',
    'DESYREL',
    'VITAMIN B-12',
    'ATROPINE SULFATE',
    'AMIKACIN SULFATE',
    'G-CSF',
    'PROVIDAL',
    'TRAMACET',
    'SINUTAB "ACHE"',
    'ZOLEDRONIC ACID',
    'TAZORAC',
    'IXABEPILONE',
    'SOLU-MEDROL',
    'CENTRUM /00554501/',
    'BLOOD PRESSURE, NAME UNKNOWN',
    'LEVSIN',
    'KLONIPIN',
    'SELENIUM',
    'GLUFAST',
    'TERAZOSIN',
    'Ribavirin',
    'BONALON 5MG',
    'MOEXIPRIL',
    'TAMSULOSIN HCL']

    mm = MetaMapLite.get_instance('/home/arios/test_pymetamap/public_mm_lite/')

    concept_1,error = mm.extract_concepts(druglist,list(range(0,len(druglist))),
    restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
    'chvs','clnd','elii','enzy','hops','horm',
    'imft','irda','inch','nnon','phsu','orch','vita'
    ])
    random.shuffle(druglist)
    concept_2,error = mm.extract_concepts(druglist,list(range(0,len(druglist))),
    restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
    'chvs','clnd','elii','enzy','hops','horm',
    'imft','irda','inch','nnon','phsu','orch','vita'
    ])
    print(len(concept_1), len(concept_2))

if __name__ == '__main__':
    main()
```

**Comment by yihengpan** [comment]
Thank you so much! I'm using metamap18 on MacOS.

**Comment by AnthonyMRios** [comment]
The problem is with the unknown (non-ascii) character in the "Botox" string. You can do something like:

```
druglist = [x.encode('ascii', 'ignore') for x in druglist]
```

before running .extract_concepts(). Currently, MetaMap is erroring (then exits) when processing the "Botox" string. That is why you get different values after shuffling.

So, it is a MetaMap issue, but it is easily fixed. Here is the MetaMap error for your information:

```
### MetaMap ERROR: MetaMap supports ASCII-only input.
The input contains 1 non-ASCII char: "�".
Remove all non-ASCII chars from input before trying again!
```

**Comment by yihengpan** [comment]
Surprised that MetamapLite doesn't have this issue!
Yes. Ignore non-ascii character works for me! Thank you so much! 
But one more question comes up, metamap seems cannot interpret the following string:

`druglist = ['PANAX GINSENG/VITAMIN A/VITAMIN B1/VITAMIN B2/VITAMIN B6/VITAMIN B12/VITAMIN C/VITAMIN D/VITAMIN E/VITAMIN B3/VITAMIN B5/VITAMIN H/VITAMIN B9/MAGNESIUM/CALCIUM/IRON/COPPER/MANGANESE/ZINC/SELENIUM/SOY (PANAX GINSENG)']`

After a kind of dumb debug, it seems can recognize druglist[0][:129] and drug[0][130:] (first 129 characters or after 130)
I don't think it's because of the string length since I have tried another longer string and it works.

I'm wondering what happened to this string. I'm not a Metamap guy and apparently need to learn a lot. Thanks a lot!

**Comment by AnthonyMRios** [comment]
Sometimes MetaMap freaks out on some inputs, i.e., it is slow. I just pushed a new update to the repo to use the prune threshold command, i.e., "--prune".

Here is what it does: "Prune Threshold: Specify the maximum number of candidate concepts used in creating final mappings. This option should be used only if MetaMap runs for a very long time."

If you install the new version of pymetamap, you can use the following command:

```
    concept_1,error = mm.extract_concepts(druglist,list(range(0,len(druglist))),
            prune=35,
            restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
            'chvs','clnd','elii','enzy','hops','horm',
            'imft','irda','inch','nnon','phsu','orch','vita'
            ])
```

**Comment by yihengpan** [comment]
Awesome! Thanks for your update! 
Emm.. I have trouble to get the newest version.
I cloned again in local and run: python setup.py install
The package seems not to be upgraded and 'prune' is still an unexpected argument...

**Comment by AnthonyMRios** [comment]
It works for me. Can you try again?

```
import random
from pymetamap import MetaMapLite
from pymetamap import MetaMap

def main():
    druglist = ['PANAX GINSENG/VITAMIN A/VITAMIN B1/VITAMIN B2/VITAMIN B6/VITAMIN B12/VITAMIN C/VITAMIN D/VITAMIN E/VITAMIN B3/VITAMIN B5/VITAMIN H/VITAMIN B9/MAGNESIUM/CALCIUM/IRON/COPPER/MANGANESE/ZINC/SELENIUM/SOY (PANAX GINSENG)']

    druglist = [x.encode('ascii', 'ignore') for x in druglist]
    print(druglist)
    #mm = MetaMap.get_instance('/home/arios/test_pymetamap/public_mm_lite/')
    mm = MetaMap.get_instance('/home/arios/metamap/public_mm/bin/metamap18')

    concept_1,error = mm.extract_concepts(druglist,list(range(0,len(druglist))),
            prune=35,
            restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
            'chvs','clnd','elii','enzy','hops','horm',
            'imft','irda','inch','nnon','phsu','orch','vita'
            ])
    #random.shuffle(druglist)
    #concept_2,error = mm.extract_concepts(druglist,list(range(0,len(druglist))),
    #restrict_to_sts=['aapp','antb','bacs','bodm','chem','chvf','rcpt',
    #'chvs','clnd','elii','enzy','hops','horm',
    #'imft','irda','inch','nnon','phsu','orch','vita'
    #])
    #print(len(concept_1), len(concept_2))
    print(len(concept_1))
    print(concept_1)

if __name__ == '__main__':
    main()
```

**Comment by yihengpan** [comment]
Yes! It works now! I've struggled with these for a couple of weeks and now everything works! 
Thank you so much for all the help!

**Comment by AnthonyMRios** [comment]
No problem. Happy to help.
