### ISSUE TITLE
Resource error: insufficient memory

### ISSUE THREAD

**Issue by xiaoleihuang** [AnthonyMRios/pymetamap#52]
I have the problem of insufficient memory. The sever memory is 256 GB, so ideally, the size is enough. I added `-Xmx16g -Xms2g` to the metamap server scripts to start the services. But I still encounter the error:
```
0it [00:00, ?it/s]! Resource error: insufficient memory
0it [02:27, ?it/s]
Traceback (most recent call last):
  File "get_concepts.py", line 133, in <module>
    process_json(task_path, task)
  File "get_concepts.py", line 110, in process_json
    results = extract_entities(documents)
  File "get_concepts.py", line 87, in extract_entities
    concepts = mm.extract_concepts(
  File "/home/xiaolei/anaconda3/lib/python3.8/site-packages/pymetamap-0.2-py3.8.egg/pymetamap/SubprocessBackend.py", line 243, in extract_concepts
    concepts = Corpus.load(output.splitlines())
  File "/home/xiaolei/anaconda3/lib/python3.8/site-packages/pymetamap-0.2-py3.8.egg/pymetamap/Concept.py", line 75, in load
    if fields[1] == 'MMI':
IndexError: list index out of range
```
Here is my function:
```python
def extract_entities(docs):
    results = []
    mm = MetaMap.get_instance('/data/tools/public_mm/bin/metamap')
    for doc in docs:
        concepts = mm.extract_concepts(
            [doc], word_sense_disambiguation=True, unique_acronym_variants=True,
            ignore_stop_phrases=True, no_derivational_variants=True,
        )
        results.append(concepts)

    # below implementation will cause insuficient memory error, even with 16G XMx
    # results = [[]] * len(docs)
    # concepts = mm.extract_concepts(docs, ids=list(range(len(docs))), word_sense_disambiguation=True)
    # for concept in concepts:
    #     results[int(concept.index)].append(concept)

    return results
```

**Comment by xiaoleihuang** [comment]
Alright. After extensive test, a better way is to follow the instructions here:

https://metamap.nlm.nih.gov/Docs/FAQ/OutOfMemory.pdf

**Comment by stefanhgm** [comment]
Hi @xiaoleihuang,

thanks for the insights. I am running into a similar issue. I tried the instructions from metamap, but I still need to set the `prune` parameter to `5` to get it working.

Could you tell me how you exactly set `I-Xmx16g -Xms2g` for metamap? I guess that could help in my case.

Thanks!

**Comment by xiaoleihuang** [comment]
> Hi @xiaoleihuang,
> 
> thanks for the insights. I am running into a similar issue. I tried the instructions from metamap, but I still need to set the `prune` parameter to `5` to get it working.
> 
> Could you tell me how you exactly set `I-Xmx16g -Xms2g` for metamap? I guess that could help in my case.
> 
> Thanks!

@stefanhgm 
You can refer to my codes, I made some revisions: [My code](https://github.com/xiaoleihuang/UserEmb_Explainable/blob/main/data/data_builder.py). I think they should be able to work in parallel. I would appreciate if you can cite my [published study of the repository](https://github.com/xiaoleihuang/UserEmb_Explainable).
