### ISSUE TITLE
installation error/Running error

### ISSUE THREAD

**Issue by nstfk** [AnthonyMRios/pymetamap#7]
Installed the package fine but it wouln't run, i am not sure if this was an installation error;
`from pymetamap import MetaMap`
it return the error

> from Concept import ConceptMMI
> ImportError: No module named 'Concept'

Any idea what went wrong and how I could fix it?

**Comment by AnthonyMRios** [comment]
Hmm... Did you install the latest version of pymetamap? What OS are you using? What version of Python are you using?

Try this:
```
$ pip uninstall pymetamap
$ git clone https://github.com/AnthonyMRios/pymetamap.git
$ cd pymetamap
$ python setup.py install
```

Then run:
```
$ python
>>> from pymetamap import MetaMap
```

**Comment by nstfk** [comment]
hey, that was quick 👍 
Running python 3.5 on windows 10. And yes I actually started to play around with it today so I just downloaded the latest version!!

**Comment by AnthonyMRios** [comment]
The code does not work with Python 3.x. It is written for Linux, not Windows. It should be easy to get it working with Windows; the SubprocessBackend will need to be changed. Specifically, I believe tempfile doesn't work with windows.

I do plan to update for python 3.5 eventually but I have been busy recently.

**Comment by nstfk** [comment]
Oh okay.. I will work it out !!
Thanks

**Comment by AnthonyMRios** [comment]
Let me know if you have any questions. Switching to Python 2.7 and changing tempfile to something else should fix your issues.

**Comment by AnthonyMRios** [comment]
This should now work with python 3.5 thanks to @joaopalotti. Please report any issues you have.
